import type { Skill } from "$lib/utils/formatSkillEffect";

/**
 * Build the `formatSkillEffect` input from a raw `skills` DB row.
 *
 * Single source for BOTH the `/skills` loader and the parity-corpus bake
 * (`website/scripts/gen-skill-effect-parity.ts`), so the mod's runtime C# port
 * is validated against the same formatter input the website renders. Mirrors the
 * object previously inlined in `website/src/routes/skills/+page.server.ts` — the
 * boolean coercions and the `pet_prefab_name` -> `pet_name` rename.
 */
export function skillRowToEffectInput(row: unknown): Skill {
  const r = row as Record<string, never>;
  return {
    id: r.id,
    skill_type: r.skill_type,
    damage_type: r.damage_type,
    max_level: r.max_level,
    damage: r.damage,
    damage_percent: r.damage_percent,
    lifetap_percent: r.lifetap_percent,
    knockback_chance: r.knockback_chance,
    stun_chance: r.stun_chance,
    stun_time: r.stun_time,
    fear_chance: r.fear_chance,
    fear_time: r.fear_time,
    aggro: r.aggro,
    is_assassination_skill: Boolean(r.is_assassination_skill),
    is_manaburn_skill: Boolean(r.is_manaburn_skill),
    break_armor_prob: r.break_armor_prob,
    heals_health: r.heals_health,
    heals_mana: r.heals_mana,
    is_resurrect_skill: Boolean(r.is_resurrect_skill),
    is_balance_health: Boolean(r.is_balance_health),
    health_max_bonus: r.health_max_bonus,
    health_max_percent_bonus: r.health_max_percent_bonus,
    mana_max_bonus: r.mana_max_bonus,
    mana_max_percent_bonus: r.mana_max_percent_bonus,
    energy_max_bonus: r.energy_max_bonus,
    defense_bonus: r.defense_bonus,
    ward_bonus: r.ward_bonus,
    magic_resist_bonus: r.magic_resist_bonus,
    poison_resist_bonus: r.poison_resist_bonus,
    fire_resist_bonus: r.fire_resist_bonus,
    cold_resist_bonus: r.cold_resist_bonus,
    disease_resist_bonus: r.disease_resist_bonus,
    damage_bonus: r.damage_bonus,
    damage_percent_bonus: r.damage_percent_bonus,
    magic_damage_bonus: r.magic_damage_bonus,
    magic_damage_percent_bonus: r.magic_damage_percent_bonus,
    haste_bonus: r.haste_bonus,
    spell_haste_bonus: r.spell_haste_bonus,
    speed_bonus: r.speed_bonus,
    critical_chance_bonus: r.critical_chance_bonus,
    critical_resist_bonus: r.critical_resist_bonus,
    accuracy_bonus: r.accuracy_bonus,
    block_chance_bonus: r.block_chance_bonus,
    fear_resist_chance_bonus: r.fear_resist_chance_bonus,
    damage_shield: r.damage_shield,
    cooldown_reduction_percent: r.cooldown_reduction_percent,
    heal_on_hit_percent: r.heal_on_hit_percent,
    healing_per_second_bonus: r.healing_per_second_bonus,
    health_percent_per_second_bonus: r.health_percent_per_second_bonus,
    mana_per_second_bonus: r.mana_per_second_bonus,
    mana_percent_per_second_bonus: r.mana_percent_per_second_bonus,
    energy_per_second_bonus: r.energy_per_second_bonus,
    energy_percent_per_second_bonus: r.energy_percent_per_second_bonus,
    strength_bonus: r.strength_bonus,
    intelligence_bonus: r.intelligence_bonus,
    dexterity_bonus: r.dexterity_bonus,
    constitution_bonus: r.constitution_bonus,
    wisdom_bonus: r.wisdom_bonus,
    charisma_bonus: r.charisma_bonus,
    duration_base: r.duration_base,
    is_invisibility: Boolean(r.is_invisibility),
    is_mana_shield: Boolean(r.is_mana_shield),
    is_cleanse: Boolean(r.is_cleanse),
    is_dispel: Boolean(r.is_dispel),
    is_teleport: Boolean(r.is_teleport),
    is_blindness: Boolean(r.is_blindness),
    is_enrage: Boolean(r.is_enrage),
    is_poison_debuff: Boolean(r.is_poison_debuff),
    is_disease_debuff: Boolean(r.is_disease_debuff),
    is_fire_debuff: Boolean(r.is_fire_debuff),
    is_cold_debuff: Boolean(r.is_cold_debuff),
    is_magic_debuff: Boolean(r.is_magic_debuff),
    is_melee_debuff: Boolean(r.is_melee_debuff),
    prob_ignore_cleanse: r.prob_ignore_cleanse,
    summoned_monster_id: r.summoned_monster_id,
    summoned_monster_name: r.summoned_monster_name,
    summoned_monster_level: r.summoned_monster_level,
    summon_count_per_cast: r.summon_count_per_cast,
    max_active_summons: r.max_active_summons,
    pet_name: r.pet_prefab_name,
    is_familiar: Boolean(r.is_familiar),
    affects_random_target: Boolean(r.affects_random_target),
    area_object_size: r.area_object_size,
    area_objects_to_spawn: r.area_objects_to_spawn,
  };
}
