using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using BetterBestiary.Skills;
using Newtonsoft.Json;
using Xunit;

namespace BetterBestiary.Tests;

/// <summary>
/// Golden parity test: the C# <see cref="SkillEffectFormatter"/> must reproduce the
/// website's <c>formatSkillEffect</c> output for every exported skill. The corpus
/// (<c>Fixtures/skill-effect-parity.json</c>) is generated by
/// <c>pnpm --filter website gen:skill-effect-parity</c> and embedded into this assembly.
/// If this fails, the port drifted from the TypeScript source of truth — fix the
/// port (or regenerate the corpus after an intentional TS change).
/// </summary>
public class SkillEffectFormatterTests
{
    private sealed class ParityCase
    {
        public string skill_id { get; set; } = "";
        public SkillEffectInput input { get; set; } = new();
        public string expected { get; set; } = "";
    }

    private static List<ParityCase> LoadCases()
    {
        var assembly = typeof(SkillEffectFormatterTests).Assembly;
        using var stream = assembly.GetManifestResourceStream("skill-effect-parity.json")
            ?? throw new InvalidOperationException(
                "skill-effect-parity.json not embedded; run `pnpm --filter website gen:skill-effect-parity`.");
        using var reader = new StreamReader(stream);
        var settings = new JsonSerializerSettings { Converters = { new LinearValueConverter() } };
        return JsonConvert.DeserializeObject<List<ParityCase>>(reader.ReadToEnd(), settings)
            ?? throw new InvalidOperationException("parity corpus deserialized to null");
    }

    [Fact]
    public void FormatterMatchesWebsiteCorpus()
    {
        var cases = LoadCases();
        Assert.NotEmpty(cases);

        var mismatches = new List<string>();
        foreach (var c in cases)
        {
            var actual = SkillEffectFormatter.Format(c.input);
            if (actual != c.expected)
                mismatches.Add($"  {c.skill_id}: expected «{c.expected}» got «{actual}»");
        }

        Assert.True(
            mismatches.Count == 0,
            $"{mismatches.Count}/{cases.Count} skills diverged from the website formatter:\n"
                + string.Join("\n", mismatches.Take(40)));
    }
}
