#!/usr/bin/env python3
"""
Stitch screenshots together into full zone maps using metadata.json.

This script reads the metadata.json file generated by MapScreenshotter and
combines all screenshots into complete zone maps with black backgrounds.
"""

import json
import os
from pathlib import Path
from PIL import Image
from collections import defaultdict

def load_metadata(screenshots_dir):
    """Load metadata.json from screenshots directory."""
    metadata_path = screenshots_dir / "metadata.json"
    if not metadata_path.exists():
        raise FileNotFoundError(f"Metadata file not found: {metadata_path}")

    with open(metadata_path, 'r') as f:
        return json.load(f)

def group_screenshots_by_zone(screenshots):
    """Group screenshots by zone name."""
    zones = defaultdict(list)
    for screenshot in screenshots:
        # Extract zone name from filename (format: ZoneName_x000_y000.png)
        filename = screenshot['file']
        zone_name = filename.rsplit('_x', 1)[0]
        zones[zone_name].append(screenshot)
    return zones

def calculate_canvas_size(screenshots, tile_size):
    """Calculate the canvas size needed for all screenshots."""
    # Get min/max of tile CENTER positions
    min_center_x = min(s['world_position']['x'] for s in screenshots)
    max_center_x = max(s['world_position']['x'] for s in screenshots)
    min_center_y = min(s['world_position']['z'] for s in screenshots)  # Note: z is Y coordinate
    max_center_y = max(s['world_position']['z'] for s in screenshots)

    # Canvas needs to span from leftmost tile edge to rightmost tile edge
    # Each tile extends tile_size/2 on each side of its center
    canvas_min_x = min_center_x - tile_size/2
    canvas_max_x = max_center_x + tile_size/2
    canvas_min_y = min_center_y - tile_size/2
    canvas_max_y = max_center_y + tile_size/2

    width_world = canvas_max_x - canvas_min_x
    height_world = canvas_max_y - canvas_min_y

    # Convert to pixels (each tile is tile_size world units = 2048 pixels)
    pixels_per_unit = 2048 / tile_size
    width_pixels = int(width_world * pixels_per_unit)
    height_pixels = int(height_world * pixels_per_unit)

    return width_pixels, height_pixels, canvas_min_x, canvas_min_y, canvas_max_x, canvas_max_y, pixels_per_unit

def stitch_zone(zone_name, screenshots, screenshots_dir, output_dir, tile_size=200):
    """Stitch all screenshots for a zone into a single image."""
    print(f"\nStitching zone: {zone_name}")
    print(f"  Screenshots: {len(screenshots)}")

    # Parse grid coordinates from filenames (world_x000_y000.png)
    # Extract X and Y tile indices
    tiles = []
    for screenshot in screenshots:
        filename = screenshot['file']
        # Extract x and y indices from filename like "world_x003_y005.png"
        parts = filename.replace('.png', '').split('_')
        x_idx = int(parts[-2][1:])  # Remove 'x' prefix
        y_idx = int(parts[-1][1:])  # Remove 'y' prefix
        tiles.append((x_idx, y_idx, filename))

    # Find grid dimensions
    max_x_idx = max(t[0] for t in tiles)
    max_y_idx = max(t[1] for t in tiles)

    # Each tile is 1024x1024 pixels
    tile_pixels = 1024
    canvas_width = (max_x_idx + 1) * tile_pixels
    canvas_height = (max_y_idx + 1) * tile_pixels

    print(f"  Grid: {max_x_idx + 1} x {max_y_idx + 1} tiles")
    print(f"  Canvas size: {canvas_width}x{canvas_height} pixels")

    # Create black background canvas
    canvas = Image.new('RGB', (canvas_width, canvas_height), color='black')

    # Paste each screenshot at its grid position
    # Game uses bottom-left origin, so y000 is at the bottom
    # Flip Y: y000 -> bottom row, max_y -> top row
    for x_idx, y_idx, filename in tiles:
        pixel_x = x_idx * tile_pixels
        pixel_y = (max_y_idx - y_idx) * tile_pixels

        # Load and paste screenshot
        screenshot_path = screenshots_dir / filename
        if screenshot_path.exists():
            img = Image.open(screenshot_path)
            canvas.paste(img, (pixel_x, pixel_y))
        else:
            print(f"  Warning: Screenshot not found: {filename}")

    # Save stitched image
    output_path = output_dir / f"{zone_name}.png"
    canvas.save(output_path, 'PNG')
    print(f"  Saved: {output_path}")
    print(f"  Size: {canvas_width}x{canvas_height} pixels")

    return output_path

def main():
    # Paths
    script_dir = Path(__file__).parent
    project_dir = script_dir.parent
    screenshots_dir = Path(os.environ.get('DATA_EXPORT_PATH', project_dir / 'exported-data')) / 'screenshots'
    output_dir = screenshots_dir / 'stitched'

    print(f"Screenshots directory: {screenshots_dir}")
    print(f"Output directory: {output_dir}")

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load metadata
    print("\nLoading metadata...")
    metadata = load_metadata(screenshots_dir)
    print(f"Found {len(metadata['screenshots'])} screenshots")
    print(f"Timestamp: {metadata['timestamp']}")

    # Group by zone
    zones = group_screenshots_by_zone(metadata['screenshots'])
    print(f"\nFound {len(zones)} zones:")
    for zone_name, screenshots in zones.items():
        print(f"  {zone_name}: {len(screenshots)} screenshots")

    # Stitch each zone
    print("\n" + "="*60)
    print("Starting stitching...")
    print("="*60)

    for zone_name, screenshots in sorted(zones.items()):
        try:
            stitch_zone(zone_name, screenshots, screenshots_dir, output_dir)
        except Exception as e:
            print(f"  Error stitching {zone_name}: {e}")
            import traceback
            traceback.print_exc()

    print("\n" + "="*60)
    print("Stitching complete!")
    print(f"Stitched maps saved to: {output_dir}")
    print("="*60)

if __name__ == '__main__':
    main()
